api/src/main/kotlin/com/mashup/dojo/common/ControllerExceptionAdvice.kt
build.gradle.kts
entity/src/main/kotlin/com/mashup/dojo/SampleEntity.kt
entity/src/main/kotlin/com/mashup/dojo/base/BaseEntity.kt
entity/src/main/kotlin/com/mashup/dojo/base/BaseTimeEntity.kt
entity/src/main/kotlin/com/mashup/dojo/config/BaseEntityConfig.kt
entity/src/main/kotlin/com/mashup/dojo/config/DojoJasyptConfig.kt
entity/src/main/kotlin/com/mashup/dojo/config/QuerydslConfig.kt
gradle.properties

- Querydsl 의존성, Spring Bean 등록하였습니다.
- BaseEntity를 BaseTimeEntity 와 BaseEntity로 나눴습니다.
- BaseEntity는 생성자, 수정자를 의미합니다.
- BaseTimeEntity는 생성 시간과 수정시간을 의미합니다. 
- JPA로 인해 생성자 및 수정자를 등록할 때 SecurityContextHolder에서 꺼내어 사용해야하지만, 우선 UUID로 두었습니다. 
추후에 BaseEntityConfig의 auditorProvider 메서드를 Principle로 수정해야합니다.
질문 및 논의는 언제나 환영입니다.

feat: Add QueryDSL configuration, split BaseEntity and BaseTimeEntity & enable JPA Auditing

---

api/src/main/kotlin/com/mashup/dojo/SampleController.kt
build.gradle.kts

[feat] 스웨거 설정을 적용해요

---

service/src/main/kotlin/com/mashup/dojo/domain/Image.kt
service/src/main/kotlin/com/mashup/dojo/service/ImageService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/ImageUseCase.kt

이미지 로드용 인터페이스 작성. (일단 Mock으로 사용하기!)

feat: 이미지 로드용 인터페이스를 작성해요

---

api/src/main/kotlin/com/mashup/dojo/QuestionController.kt
api/src/main/kotlin/com/mashup/dojo/dto/QuestionDto.kt
service/src/main/kotlin/com/mashup/dojo/domain/Question.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultQuestionService.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- ref : https://github.com/mash-up-kr/Dojo-Spring/issues/12
- 질문지 생성에 대한 mock API 작성하였습니다. 
- 지난 번 이야기 나눈대로 entity 부분은 우선 샘플로 만들도록 하였습니다.

feat : create Question Mock Api

---

api/src/main/kotlin/com/mashup/dojo/SampleController.kt
entity/src/main/kotlin/com/mashup/dojo/ImageRepository.kt
entity/src/main/kotlin/com/mashup/dojo/SampleEntity.kt
entity/src/main/kotlin/com/mashup/dojo/SampleRepository.kt
entity/src/main/kotlin/com/mashup/dojo/base/BaseTimeEntity.kt
service/src/main/kotlin/com/mashup/dojo/domain/Image.kt
service/src/main/kotlin/com/mashup/dojo/domain/Member.kt
service/src/main/kotlin/com/mashup/dojo/domain/Pick.kt
service/src/main/kotlin/com/mashup/dojo/domain/Question.kt
service/src/main/kotlin/com/mashup/dojo/domain/QuestionSet.kt
service/src/main/kotlin/com/mashup/dojo/domain/Sample.kt
service/src/main/kotlin/com/mashup/dojo/service/ImageService.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/service/SampleService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/SampleUseCase.kt

- BaseTimeEntity 에 id 프로퍼티 제거
- 각 entity모델에 id 별도 정의
- 모든 도메인 모델 id type string type id 로 변경

feat; 모든 도메인 모델의 id를 string type으로 바꿔요

---

_endpoint_test/getQuestionSheet.http
api/src/main/kotlin/com/mashup/dojo/SheetController.kt

getQuestionSheer API Swagger + getQuestionSheer API .http

add: 질문목록 12개를 반환하는 API Swagger를 작성해요.

---

_endpoint_test/question.http
api/src/main/kotlin/com/mashup/dojo/QuestionController.kt
api/src/main/kotlin/com/mashup/dojo/dto/QuestionDto.kt
service/src/main/kotlin/com/mashup/dojo/domain/QuestionSet.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- QuestionSet 를 custom 생성할 수 있도록 API 제공합니다. 
- 기존 Question API 에 대해 누락한 http 테스트 완료하였습니다.

add : create custom questionSet API

---

_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MemberCreateRequest.kt
api/src/main/kotlin/com/mashup/dojo/dto/MemberDto.kt
common/src/main/kotlin/com/mashup/dojo/UUIDGenerator.kt
entity/src/main/kotlin/com/mashup/dojo/MemberRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/Member.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

feat; 멤버 가입(등록) API 작성하기

---

.ebextensions/healthcheck.config
.github/workflows/cd.yaml
api/src/main/kotlin/com/mashup/dojo/HealthController.kt
build.gradle.kts
deploy/Procfile

#41 
- release/** 브랜치에 코드가 푸시되면 AWS Elastic Beanstalk을 사용해 CD가 수행됩니다.
- cf) https://github.com/xonmin/aws-freetier-cdktf-template

add: CD workflow

---

build.gradle.kts
gradle.properties

QueryDSL 의존성을 수정했습니다.
`./gradlew clean build` 사용하면 QClass 가 생성됩니다.
`entity/generated/source/kapt/main/com/maship/dojo` 에 생성되며 clean 하면 사라지도록 했습니다.

fix: 잘못된 QueryDSL 의존성으로 QClass 가 생성되지 않는 것을 수정했습니다.

---

api/src/main/kotlin/com/mashup/dojo/config/security/WebSecurityConfiguration.kt
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/Pick.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

1. PickEntity table 필드명을 sname 형태로 변경했습니다.
2. Pick domain, Entity, Service, Usecase에 QuestionSetId, QuestionSheetId 필드를 추가했습니다.
Pick 생성시에 사용되는 QuestionSetId, QuestionSheetId를 현재 사용자 정보로 redis에서 추출해야합니다.

feat: add pick domain table

---

api/src/main/kotlin/com/mashup/dojo/config/WebConfiguration.kt

1. CORS Filter, UrlBasedCorsConfigurationSource를 도입하여 CORS를 제어합니다.
2. HTTP OPTIOANS 메서드 추가했습니다.
3. AllowHeader에는 Content-Type, Authorization, X-Requested-With를 추가했습니다.
4. 제공된 도메인의 뒷 주소는 모두 허용합니다.

fix: cors allow config

---

_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MemberProfileResponse.kt
entity/src/main/kotlin/com/mashup/dojo/MemberRelationRepository.kt
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberRelationService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

타인의 프로필을 조회하는 API 구현했습니다.
1. 픽 조회 API PR #75 에서 사용하던 로직을 재사용하기 위해 base를 PR #75 로 잡고 작업했습니다.
[feat: user's pick count query](https://github.com/mash-up-kr/Dojo-Spring/pull/76/commits/f348343b5144e52a34f6b3e65a68d1bbda7a5378) https://github.com/mash-up-kr/Dojo-Spring/pull/76/commits/f348343b5144e52a34f6b3e65a68d1bbda7a5378 부터 봐주시면 좋을 것 같습니다.
2. 현재 프로필 조회시 5번(타겟 멤버, 이미지, 픽 카운트, 친구 여부, 친구수 카운트) 쿼리가 발생하는데, 추후에 수정하면 좋을 것 같습니다.
팀원분들은 어떻게 해결하시는지 궁금합니다..!

feat: 타인 프로필 조회 API

---

api/src/main/kotlin/com/mashup/dojo/AdminController.kt
api/src/main/kotlin/com/mashup/dojo/dto/QuestionDto.kt
entity/src/main/kotlin/com/mashup/dojo/QuestionSetRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/QuestionSet.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- QSet 내에 PickTime 의 (publish / end At) 정보를 가지고 있도록 변경합니다. 
- 따라서 QSet 을 만들 떄는 마지막 이전 endAt 을 publishAt 타임으로 가지게 됩니다.

add endTime in Qset

---

api/src/main/kotlin/com/mashup/dojo/scheduler/Scheduler.kt
entity/src/main/kotlin/com/mashup/dojo/MemberRelationRepository.kt
entity/src/main/kotlin/com/mashup/dojo/QuestionRepository.kt
entity/src/main/resources/application-entity.yaml
service/src/main/kotlin/com/mashup/dojo/domain/Question.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberRelationService.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt
service/src/main/resources/application.yaml

QuestionSheet 생성 로직을 구현했습니다. 친구 관계의 질문은 친구 중에서, 비친구 관계의 질문은 비친구 중에서 완전 무작위로 후보자를 선택하는 방식이 예전에 정했던 방법 같아서 그렇게 진행했습니다.
아래와 같이 동작합니다. 혹시나 잘못되거나 틀린 점 있으면 말씀해주세요!
1. 모든 Member를 DB에서 조회합니다.
2. 각 Member에 대해 친구와 비친구를 구분하여 해당 후보자를 가져오는 쿼리를 실행합니다.
3. QuestionSet의 questionIds를 List<친구 질문>과 List<비친구 질문>으로 구분합니다.
4. 분류된 질문 목록과 각각의 후보자를 매칭하여 List<QuestionSheet>를 생성합니다.
5. 생성된 QuestionSheet들을 두 리스트를 합쳐서 반환합니다.
6. `List<QuestionSheet>`를 `List<QuestionEntity>`로 변환하여 DB에 저장후 다시 `List<QuestionSheet>`로 변환하여 반환합니다.
쉽게 설명하려다 보니 좀 길어졌네요,, 긴 글 읽어 주셔서 감사합니다
현재 친구 수가 8명 미만인 경우 오류가 발생해서, QuestionSheet를 생성하는 스케줄러를 일시적으로 주석 처리하였습니다. 추후 친구 관계가 설정된 이후에 주석을 해제할 예정입니다.

feat: Create QuestionSheet

---

_endpoint_test/http-client.env.json
_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MyProfileResponse.kt

feat; 본인 프로필 조회 API 를 추가해요. (mock 응답)

---

entity/src/main/kotlin/com/mashup/dojo/QuestionSetRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt

- QSheet 만들어졌는지 확인하려했는데, EB 들어가보니 에러로그 확인되어 버그 수정합니다. 
```
Aug 16 00:05:00 ip-172-31-12-84 web[391860]: 2024-08-16 09:05:00.144 ERROR 391860 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
Aug 16 00:05:00 ip-172-31-12-84 web[391860]: org.springframework.dao.IncorrectResultSizeDataAccessException: Query did not return a unique result: 4 results were returned
Aug 16 00:05:00 ip-172-31-12-84 web[391860]: #011at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:301)
Aug 16 00:05:00 ip-172-31-12-84 web[391860]: #011at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244)
Aug 16 00:05:00 ip-172-31-12-84 …
```

fix : 운영/발행예정 QSet 조회 쿼리 수정

---

_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/resources/application.yaml
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt
service/src/main/resources/application.yaml

1. 기존 #86 에서 작업을 시작했습니다.
2. 마이스페이스에서 내가 받은 픽을 조회하는 API 만들었습니다.
3. 공동 등수를 고려하여 계산 후 반환합니다.
이번 리뷰도 잘 부탁드립니다. ☺️

feat: 마이스페이스 내가 받은 픽 API

---

_endpoint_test/pick.http
api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/dto/PickDto.kt
common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/Pick.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

1. 기존 모든 픽을 반환하던 것을 페이징처리하여 반환합니다.
2. 기존 N + 1 문제가 발생하던 것을 조인하여 2번의 쿼리로 한 번에 처리합니다.
3. pickDetail 페이징과 객체명이 혼란스러워 pickPaging 과 pickDetailPaging으로 구분했습니다.

feat: picklist paging logic

---

api/src/main/kotlin/com/mashup/dojo/config/security/JwtTokenService.kt
api/src/main/kotlin/com/mashup/dojo/config/security/MemberAuthTokenAuthenticationFilter.kt

Authorization Header에서 JWT Token 추출시 Bearer prefix를 제거하지 않아 인증 되지 않던 문제를 해결했습니다.

fix: token parsing issue by removing Bearer prefix and trimming spaces

---

api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MyProfileResponse.kt
common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt

내 정보 조회하기 원래 mock이었는데 요청한 멤버의 정보 내리되, count값만 목으로 냄겨놔요

feat; 내 정보 조회 시 카운트 값만 Mock으로 내려요

---

service/src/main/kotlin/com/mashup/dojo/usecase/MemberRelationUseCase.kt

feat; 친구 목록 조회 시 한글 오름차순 정렬해요

---

api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/dto/PickDto.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt

pickId, pickerId, pickerGender, pickerPlatform, pickerSecondInitialName, pickerFullName
pickId, pickerId, pickerGender, pickerPlatform, pickerSecondInitialName, pickerFullName  필드를 UNKNOWN에서 null로 수정했습니다.

fix: pick detail field UNKNOWN to null

---

entity/src/main/kotlin/com/mashup/dojo/QuestionSetRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/QuestionSet.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

QSheet 생성 스케줄 동작시, 이미 만들어진 QSet 이 다중으로 모두 배포 예정 이전일 때, 가장 현재에 가까운 QSet 을 계속 가져와 만들어지고 있는 문제 수정 
- QSet Enum 값 READY (QSheet 생성 완료) 값 신규 추가 
- QSheet 스케쥴 동작시, 사용한 QSet status 값 업데이트하도록 변경 
테스트 완료했고 잘 만들어지는 것까지 확인했습니다. 
```sql 
select question_set_id,  count(*)
from question_sheet
group by question_set_id
12 개 * 81 명 = 972 
```

QSheet 생성시 사용된 QSet 상태 변경

---

_endpoint_test/pick.http
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

- pick NextOpenTime 에 대해서 다음 발행 예정인 QSet publishTime 을 사용하도록 변경하였습니다.

[update] pick open time using QSet publishedAt

---

api/src/main/kotlin/com/mashup/dojo/dto/QuestionDto.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- 질문지 조회시, questionOrder 순으로 응답이 안내려가고 있어 sorting 합니다
- 응답에서 questionOrder 를 1based 로 수정합니다.

update : questionSheet 조회시 order sort

---

_endpoint_test/coin.http
api/src/main/kotlin/com/mashup/dojo/CoinController.kt
api/src/main/resources/application.yaml
service/src/main/kotlin/com/mashup/dojo/usecase/CoinUseCase.kt

현재 운영중인 QuestionSet에서 본인의 질문지 중 픽한 개수만큼 지급된 코인을 반환하는 API입니다.

feat: 현재 운영중인 QuestionSet에서 총 지급된 coin 반환 API

---

entity/src/main/kotlin/com/mashup/dojo/MemberRelationRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberRelationService.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

지난 미팅 때 나온 비즈니스 로직 결함으로 질문 카테고리 중 전체에 해당하는 질문에는 후보자를 전체로 변경합니다.

fix : 전체 대상에 대한 질문에 대해선 후보자 친구+비친구로 변경

---

api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/dto/PickDto.kt
service/src/main/kotlin/com/mashup/dojo/usecase/CoinUseCase.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

add: 픽 스킵 기능 추가

---

_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MemberCreateRequest.kt
common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
service/src/main/kotlin/com/mashup/dojo/domain/MemberRelation.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberRelationService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

친구 해제 API 를 작성해요.
친구 추가 API와 비슷한 형태로 만들었어요!

feat: 친구 해제 API를 작성해요.
