.github/CODEOWNERS
.github/workflows/ci.yaml
entity/src/main/kotlin/com/mashup/dojo/config/DojoJasyptConfig.kt

- 1 CI - 기본적인 build check 을 위해 github-actions ci 를 추가하였습니다 .
- 2 CodeOwners - PR review 에 자동으로 등록될 수 있도록 codeowners 추가하였습니다.
- CI build 에서 ktlint 검열 정상 동작하는 것 확인하였습니다. 
@wonlog-g 님 이름만 보라색으로 나오는데, 이유는 모르겠습니다..ㅎㅎ

feat :  GitHub actions ci & CodeOwners

---

service/src/main/kotlin/com/mashup/dojo/domain/Member.kt
service/src/main/kotlin/com/mashup/dojo/domain/MemberRelation.kt
service/src/main/kotlin/com/mashup/dojo/domain/Pick.kt
service/src/main/kotlin/com/mashup/dojo/domain/Question.kt
service/src/main/kotlin/com/mashup/dojo/domain/QuestionSet.kt

feat; phase1 의 도조 도메인 모델들을 정의해요

---

service/src/main/kotlin/com/mashup/dojo/usecase/ImageUseCase.kt

- https://github.com/mash-up-kr/Dojo-Spring/pull/18#discussion_r1659643316
- `Impl` suffix 를 `Default` prefix 로 네이밍 규칙 정하여 변경합니다. 
-

rename : imageUsecase concreate comp to Default prefix

---

api/src/main/kotlin/com/mashup/dojo/QuestionController.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- ref : https://github.com/mash-up-kr/Dojo-Spring/pull/17 
- 질문지 생성 API 에 이어 bulk 로 질문지 생성할 수 있도록 mock Api 작업 하였습니다.

add : bulk create question api

---

service/src/main/kotlin/com/mashup/dojo/domain/Image.kt
service/src/main/kotlin/com/mashup/dojo/domain/Question.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultQuestionService.kt
service/src/main/kotlin/com/mashup/dojo/service/ImageService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/ImageUseCase.kt

- Question 내 카테고리 분류를 위해 QuesitonCategory 를 추가합니다. 
- Image 를 sealed class 로 분류하고, UserImage 와 EmojiImage 로 세분화 합니다.

update : add category in question & update Image to sealed class

---

service/src/main/kotlin/com/mashup/dojo/domain/Image.kt
service/src/main/kotlin/com/mashup/dojo/service/ImageService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/ImageUseCase.kt

- 논의에 따라 Image 분류되어있던 것을 다시 원복합니다.

revert : user image , emoji image 분리

---

api/src/main/kotlin/com/mashup/dojo/QuestionController.kt

question post mapping path 중복 fix 합니다.

fix : bulk create question api url

---

api/src/main/kotlin/com/mashup/dojo/config/SchedulerConfig.kt
api/src/main/kotlin/com/mashup/dojo/scheduler/Scheduler.kt
api/src/main/kotlin/com/mashup/dojo/scheduler/SchedulerBasePackage.kt
service/src/main/kotlin/com/mashup/dojo/domain/QuestionSet.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- QuestionSet 에 대해서 Scheduler 를 통해 만드는 베이스코드 작성하였습니다. 
- 현재 global cache / entity 레벨 붙은게 없어서 내부 로직이 없어 후속으로 진행합니다 .
- QuestionSheet 에서 QuestionSet sample data 조회를 위해 먼저 PR 엽니다. 
+ custom 하게 QuestionSet 만들 수 있도록 이후 추가 API 만듭니다.

feat : create QuestionSet Mock api

---

_endpoint_test/http-client.env.json
_endpoint_test/image.http
api/src/main/kotlin/com/mashup/dojo/ImageController.kt
build.gradle.kts
common/src/main/kotlin/com/mashup/dojo/external/ExternalConfiguration.kt
common/src/main/kotlin/com/mashup/dojo/external/aws/ImageUploadUrlProvider.kt
common/src/main/resources/application-common.yaml
entity/src/main/kotlin/com/mashup/dojo/ImageRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/Image.kt
service/src/main/kotlin/com/mashup/dojo/service/ImageService.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/ImageUseCase.kt

- 이미지 업로드 정보 조회 API 작성
- 이미지 업로드 위한 presigned url 제공.
- 서버엔 별도로 image id / uuid / url 저장

feat; 이미지 업로드 정보 조회 API 작성해요 (presigned url 활용)

---

service/src/main/kotlin/com/mashup/dojo/domain/Question.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/SheetUseCase.kt

질문 카테고리에 대해서 notion 내 정리된 카테고리로 업데이트 합니다.

fix : Question Category update

---

api/src/main/kotlin/com/mashup/dojo/AdminController.kt
api/src/main/kotlin/com/mashup/dojo/QuestionController.kt

- Question 관련 api 에 대해서 admin 권한이 필요한 경우, admin API 를 통해 처리할 수 있도록 별도로 분리합니다.

add : admin api adminController 로 이관

---

entity/src/main/kotlin/com/mashup/dojo/ImageRepository.kt

- image entity 에 대해 Table / Cols 명세하는 것으로 업데이트합니다.

update : image entity cols

---

api/src/main/resources/application.yaml
api/src/main/resources/logback-spring.xml

feat: connect logback, cloudwatch

---

common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
entity/src/main/kotlin/com/mashup/dojo/MemberRelationRepository.kt
entity/src/main/resources/application-entity.yaml
service/src/main/kotlin/com/mashup/dojo/domain/MemberRelation.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberRelationService.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberService.kt

- application-entity.yml에서 잘못된 hibernate 설정으로 생성되지 않는 문제를 수정했습니다.
- MemberRelation entity를 추가했습니다.
- 관계 생성(관리자)시 비친구로 관계 생성하도록 했습니다.
- 친구 업데이트 기능 만들었습니다.
Entity - Domain 변환 로직 작성했는데 잘못되거나 틀린 부분 있으면 말씀해주세요!

add MemberRelation entity

---

build.gradle.kts

환경변수를 env 파일로 접근할 때는 됐지만 edit configuration에서 추가할 땐 안되는 현상을 발견했습니다.
외부 라이브러리 의존성을 추가해서 해결했습니다.

feat: 환경변수 xml에 자동 주입해주는 의존성 추가

---

entity/src/main/kotlin/com/mashup/dojo/CoinRepository.kt
entity/src/main/kotlin/com/mashup/dojo/CoinUsecase.kt
entity/src/main/kotlin/com/mashup/dojo/MemberRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/Coin.kt
service/src/main/kotlin/com/mashup/dojo/domain/Member.kt
service/src/main/kotlin/com/mashup/dojo/service/CoinService.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/CoinUseCase.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

- coin 관련 Entity 를 추가했습니다. 
- 회원가입 시 기본 코인 정보를 생성합니다.
부족한 부분 틀린 부분 빠진 부분 궁금한 부분 질문주세요

add coin/CoinUseDetail entity

---

api/src/main/kotlin/com/mashup/dojo/AdminController.kt
api/src/main/kotlin/com/mashup/dojo/dto/QuestionDto.kt
common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
entity/src/main/kotlin/com/mashup/dojo/QuestionRepository.kt
entity/src/main/kotlin/com/mashup/dojo/QuestionSetRepository.kt
entity/src/main/kotlin/com/mashup/dojo/QuestionSheetRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/Question.kt
service/src/main/kotlin/com/mashup/dojo/domain/QuestionSet.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt
service/src/main/kotlin/com/mashup/dojo/usecase/SheetUseCase.kt

- Question / QuestionSet/ QuestionSheet 기본적인 entity 작업 진행 
- custom QuestionSet 생성 로직 추가 
- QuestionSet 조회 로직 추가

add question's entity

---

_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/config/WebSecurityConfiguration.kt
api/src/main/kotlin/com/mashup/dojo/config/security/JwtTokenService.kt
build.gradle.kts

- jwt 기반 토큰 발급 서비스 작성
- public 멤버 회원가입 / 로그인 API 작성
- 회원가입은 추후 우리가 정보 하나씩 넣을 용도
- 로그인 API는 auth token 발급용 입니다!

feat; jwt 기반 토큰 발급 서비스를 작성하고, 멤버 회원가입/로그인 API를 작성해요.

---

api/src/main/kotlin/com/mashup/dojo/config/WebConfiguration.kt

제목과 같아요. 웹쪽은 포트 5173으로 로컬 작업하신다고하네용!

[feat] localhost:5173 CORS 허용해요

---

api/src/main/kotlin/com/mashup/dojo/AdminController.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- question 관련 create method 들에 대해서 누락된 tx annotation 추가해줍니다.

fix : create question tx

---

service/src/main/kotlin/com/mashup/dojo/domain/Member.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberService.kt

- memberService.findByMemberId() 에 mock 로직이 들어있었는데 이걸 제거해요.
- memberService에 MemberEntity.toMember() 확장함수를 정의하고 활용해요

feat; memberService.findByMemberId() 로직을 구현해요

---

_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MemberLoginRequest.kt

- 제목과 같아요. FE 요청으로 GET -> POST 로 메소드 변경

[feat] 멤버 로그인 API의 HTTP Method를 변경해요

---

api/src/main/kotlin/com/mashup/dojo/PickController.kt
common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
entity/src/main/kotlin/com/mashup/dojo/PickTimeRepository.kt
service/src/main/kotlin/com/mashup/dojo/domain/PickTime.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

feat: 다음 투표 시간 조회

---

api/src/main/kotlin/com/mashup/dojo/config/security/WebSecurityConfiguration.kt

- 로그인 API (public) 는 잘 요청되고, 그 외 API는 CORS 에러가 난다해서 우선 필터를 임시로 지워봐요.

fix; auth filter 임시 제거

---

api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/dto/PickDto.kt
api/src/main/kotlin/com/mashup/dojo/dto/QuestionDto.kt
common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

Pick 에 추가된  QSetId , QSheetId 에 대해서 Pick 생성 API 에서 적용합니다.

update : pick 생성 시, QuestionSetId, QuestionSheetId 추가

---

.platform/nginx/conf.d/elasticbeanstalk/00_application.conf
.platform/nginx/conf.d/nginx.conf

1. 기존 묵시적이던 nginx.conf를 명시적으로 선언했습니다.
2. 기존 로드밸런서에 새로운 도메인을 추가하여 ACM 인증서 생성 후 https를 적용했습니다.
3. http 리스너를 삭제하여 https로만 통신할 수 있도록 했습니다.
https://docker-ecs.net//swagger-ui/index.html#

fix: https 적용 및 nginx.conf 적용

---

api/src/main/kotlin/com/mashup/dojo/config/security/WebSecurityConfiguration.kt

fix; 인증 필터 다시 넣어요

---

api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/dto/PickDto.kt
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

1. Pick을 페이징처리하여 조회하는 query를 작성했습니다.
2. 기존 PickUseCase에서 사용하던 Pick 데이터 변환 및 UNKNOWN(픽이 오픈되지 않은 상태)처리를 DefaultPickService에서 사용하도록 수정했습니다.

feat: pick details list logic

---

api/src/main/kotlin/com/mashup/dojo/config/security/MemberAuthTokenAuthenticationFilter.kt

필터 제외 path에 health 추가하기

---

_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

현재 data가 없기 때문에, 정상적으로 동작할 것 같지 않아서 PR #76 에서 작업한 타인 프로필 조회에 대한 Mock Api를 작성했습니다.

feat: 타인 프로필 조회 Mock API

---

entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- QSheet 조회 요청에 대해서 내가 QSheet 내 푼 문제에 대해서 있는 지 조회하는 메서드 구현하였습니다.

update : solvedPick impl

---

api/src/main/kotlin/com/mashup/dojo/scheduler/Scheduler.kt
api/src/main/resources/application.yaml
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt
service/src/main/resources/application.yaml

친구 관계 생성 완료하여 기존 QSheet 스케줄러 활성화합니다.

update : activate QSheet create scheduler

---

_endpoint_test/member.http
api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MemberCreateRequest.kt
service/src/main/kotlin/com/mashup/dojo/domain/MemberRelation.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberRelationService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

- ~~기존에 멤버는 만들었나 기본관계(ACCOMPANY)는 없어서 bulk 용 API 만들었습니다.~~
- 임시 bulk 용이라서 다시 제거하였습니다
- 회원가입시에 기본관계를 만들기 위해 회원가입에 추가하였습니다.
- follow (친구 관계 생성)에 대한 API 만들었습니다. 
- 해당 API 를 통해 우선 기본 스펙이었던 플랫폼/프로젝트 팀원간 친구관계는 먼저 만들어 두었습니다. 
카카오톡 내용 확인

add relationship api

---

service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

QSet 생성 배치에서 불필요하게 제외해야할 QSet 정보를 두번 조회하고 있어 param 으로 받은 데이터로 수정합니다.

refactor : excludeQSet to latestQset in create QSet

---

api/src/main/kotlin/com/mashup/dojo/MemberRelationController.kt
api/src/main/kotlin/com/mashup/dojo/dto/FriendInfoResponse.kt
service/src/main/kotlin/com/mashup/dojo/service/ImageService.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberRelationUseCase.kt

내 친구 목록을 조회합니다. (relationType = friend)
추천 친구 목록을 조회합니다. (relationType = accompany)

feat: 내 친구 리스트 조회 & 추천 친구 리스트 조회

---

api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MemberSearchResponse.kt
common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
entity/src/main/kotlin/com/mashup/dojo/MemberRelationRepository.kt
entity/src/main/kotlin/com/mashup/dojo/MemberRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberRelationService.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

친구, 친구 아닌 사람 모두 검색 가능한 통합 검색 기능입니다.

feat: 멤버 검색

---

_endpoint_test/notification.http
api/src/main/kotlin/com/mashup/dojo/NotificationSseController.kt
build.gradle.kts
service/src/main/kotlin/com/mashup/dojo/service/NotificationService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

- SSE 를 이용해 알림을 보내고자해요.
- 우선 pick이 생성되면 pick 대상자에게 event를 발송하는 것부터 시작해요.
- create pick 을 직접 호출하려했는데 지금 디비 상 데이터가 따로 없어서 우선 테스트용 api로 테스트했어욘

feat; pick 을 생성하면 pick 대상에게 알림을 보내요. (SSE기반)

---

entity/src/main/kotlin/com/mashup/dojo/QuestionSheetRepository.kt

- entity 상속이 빠져있어서 수정합니다. 
- QSheet 생성 테스트에 있어서 candidate varchar 로 되어있던 부분 text 로 수정했습니다.

fix : QuestionSheet 엔티티 baseTimeEntity 상속

---

common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
deploy/Procfile
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt

1. QuestionService에 있는 mock findById를 제거하고 실제 값으로 사용합니다.
2. UTF-8로 인코딩하여 한글 인코딩이 안되는 것을 수정합니다.

fix: encoding utf-8, findById question remove mock

---

api/src/main/kotlin/com/mashup/dojo/config/SchedulerConfig.kt
api/src/main/kotlin/com/mashup/dojo/scheduler/Scheduler.kt
api/src/main/resources/application.yaml
build.gradle.kts
entity/src/main/kotlin/com/mashup/dojo/QuestionSetRepository.kt
entity/src/main/kotlin/com/mashup/dojo/QuestionSheetRepository.kt

1. 비동기 처리 방식을 해제했습니다.
2. 클러스터 환경에서 올바르게 작동하기 위해 SheedLock을 사용합니다.

fix: scheduler config

---

build.gradle.kts
common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

1. QuestionSet을 처음 갖고올 때 1번만 질문들마다 Type을 분류
2. 각 member에 대해 매 질문마다 친구/비친구 후보자 추출

fix: 질문마다 후보자를 다르게 설정

---

api/src/main/kotlin/com/mashup/dojo/CoinController.kt
api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/QuestionController.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberService.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/QuestionUseCase.kt

- todo  로 작성되어있던 user id param ContextHolder 에서 뽑도록 변경 
- delete unused code 
- 시트지조회(GetQuestionSheet) mock response 제거

update : todo user id param / delete unused code / 시트지조회 mock 제거 

---

_endpoint_test/pick.http
_endpoint_test/question.http

- question / pick post http 수정합니다.

update : question / pick http requestbody

---

api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/dto/PickDto.kt
api/src/main/resources/application.yaml
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt

1. 오픈 여부에 따라 프로필 이미지를 반환합니다.
2. 남성, 여성, 기본 프로필 이미지를 Jasypt로 암호화하여 반환합니다.

feat: pickerProfileImageUrl

---

api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/dto/PickDto.kt
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

사용하지 않는 anyOpenPickerCount를 제거했습니다.

fix: unused remove anyOpenPickerCount query, field

---

api/src/main/kotlin/com/mashup/dojo/PickController.kt
api/src/main/kotlin/com/mashup/dojo/dto/PickDto.kt
service/src/main/kotlin/com/mashup/dojo/domain/Coin.kt
service/src/main/kotlin/com/mashup/dojo/domain/Pick.kt
service/src/main/kotlin/com/mashup/dojo/service/CoinService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

add: 코인 사용 로직 추가

---

service/src/main/kotlin/com/mashup/dojo/usecase/MemberRelationUseCase.kt

친구 목록 응답 시 사용자 프로필 이미지 조회 로직 수정했습니다.

mod: 프로필 이미지 조회 로직 수정

---

service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

멤버 검색 쪽 이미지 반환 작업 누락하여 추가했습니다.

mod: 이미지 없는 경우 default 이미지 url 반환

---

api/src/main/kotlin/com/mashup/dojo/MemberController.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

#87 이랑 로직과 response가 100% 동일해서 로직을 그대로 사용했습니다.

feat: 친구 스페이스 친구가 받은 픽 API 추가, 기존 마이스페이스 - 내가 받은 픽 기능 재사용

---

api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/SpaceResponse.kt

fix: SpaceResponse docs

---

api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MyProfileResponse.kt
entity/src/main/kotlin/com/mashup/dojo/MemberRelationRepository.kt
entity/src/main/kotlin/com/mashup/dojo/PickRepository.kt
service/src/main/kotlin/com/mashup/dojo/service/DefaultPickService.kt
service/src/main/kotlin/com/mashup/dojo/service/MemberRelationService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

제목과 같아요. 각종 카운트 값들 추가
거의 다 만들어져있어서, friend count만 추가했어용

feat; 내 정보 조회 시 각종 카운트값을 함께 조회할 수 있어요

---

common/src/main/kotlin/com/mashup/dojo/DojoExceptionType.kt
service/src/main/kotlin/com/mashup/dojo/service/QuestionService.kt

친구/비친구 후보자가 기본 후보자수보다 적다면 후보자 바꿔주는 작업을 추가했습니다.

fix: 친구/비친구 후보자수가 적다면 후보자 바꿔주는 작업 추가

---

api/src/main/kotlin/com/mashup/dojo/MemberController.kt
api/src/main/kotlin/com/mashup/dojo/dto/MyProfileResponse.kt
service/src/main/kotlin/com/mashup/dojo/usecase/MemberUseCase.kt

1. 마이페이지에서 코인 정보를 제거했습니다.
2. 비즈니스 로직을 UseCase로 이동했습니다.

fix: remove coin, 비즈니스 로직 UseCase로 이동

---

api/src/main/resources/application.yaml

feat: set jar time-zone Asia/seoul

---

api/src/main/kotlin/com/mashup/dojo/common/TimeLogger.kt

feat: TimeLogger

---

api/src/main/kotlin/com/mashup/dojo/common/ControllerExceptionAdvice.kt

eat AsyncRequestTimeoutException

fix: eat AsyncRequestTimeoutException

---

api/src/main/kotlin/com/mashup/dojo/CoinController.kt
service/src/main/kotlin/com/mashup/dojo/domain/Coin.kt
service/src/main/kotlin/com/mashup/dojo/service/CoinService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/CoinUseCase.kt

add : 투표 완료 잼 API

---

api/src/main/kotlin/com/mashup/dojo/config/security/MemberAuthTokenAuthenticationProvider.kt

fix: dojo 팀원이 아닐 경우 예외 발생

---

service/src/main/kotlin/com/mashup/dojo/service/CoinService.kt
service/src/main/kotlin/com/mashup/dojo/usecase/PickUseCase.kt

add reword complete pick

---

api/src/main/kotlin/com/mashup/dojo/CoinController.kt
api/src/main/resources/application.yaml
service/src/main/kotlin/com/mashup/dojo/usecase/CoinUseCase.kt

1. 투표 완료를 통한 잼 휙득 API 제거
2. 관리자 확인 로직 변경

fix: remove earncoinapi & validadmin policy
